"""songs, stems, jobs

The first migration: the three tables T-1.4 owns. Chapter 5 lists five more
(lyrics, lyric_lines, library_items, user_song_settings, usage_quota); they
arrive with the tasks that use them.

Worth knowing when reading the DDL below:

- the vocabularies are CHECK constraints over varchar, not native enum types,
  so that adding a state later is an ordinary migration with a downgrade that
  works, and so the schema stays portable while D-15 is open;
- every constraint and index is named by the convention in packages/core/db.py.
  Postgres will happily name them itself, and then the downgrade cannot drop by
  name what it did not name;
- ids default to gen_random_uuid() in the database, not only in Python, so
  inserts that bypass the ORM still get an id;
- jobs.user_id has no foreign key. Users belong to a managed auth provider and
  D-16 is not decided yet.

Revision ID: 1fe75bcef4e6
Revises:
Create Date: 2026-08-18 15:50:26.610391

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fe75bcef4e6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("artist", sa.Text(), nullable=True),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("original_key", sa.String(length=8), nullable=True),
        sa.Column("bpm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_playable", sa.Boolean(), nullable=False),
        sa.Column("lyrics_status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lyrics_status IN ('pending', 'line', 'word', 'missing')",
            name=op.f("ck_songs_lyrics_status"),
        ),
        sa.CheckConstraint("source_type IN ('file', 'url')", name=op.f("ck_songs_source_type")),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'ready', 'failed')", name=op.f("ck_songs_status")
        ),
        sa.CheckConstraint(
            "duration_sec IS NULL OR duration_sec <= 480", name=op.f("ck_songs_duration_max")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_songs")),
        sa.UniqueConstraint("content_hash", name="uq_songs_content_hash"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("current_step", sa.String(length=32), nullable=True),
        sa.Column("progress", sa.SmallInteger(), nullable=False),
        sa.Column("remote_call_id", sa.String(length=128), nullable=True),
        sa.Column("gpu_seconds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_step IS NULL OR current_step IN ('ingesting', 'separating', 'transcribing_mix', 'transcribing_vocals', 'encoding', 'aligning')",
            name=op.f("ck_jobs_current_step"),
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'ready', 'failed')", name=op.f("ck_jobs_state")
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name=op.f("ck_jobs_progress_range")),
        sa.ForeignKeyConstraint(
            ["song_id"], ["songs.id"], name=op.f("fk_jobs_song_id_songs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_song_id", "jobs", ["song_id"], unique=False)
    op.create_index("ix_jobs_user_id_state", "jobs", ["user_id", "state"], unique=False)
    op.create_table(
        "stems",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('vocals', 'drums', 'bass', 'other')", name=op.f("ck_stems_kind")
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["songs.id"], name=op.f("fk_stems_song_id_songs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stems")),
        sa.UniqueConstraint("song_id", "kind", name="uq_stems_song_id_kind"),
    )
    op.create_index(op.f("ix_stems_song_id"), "stems", ["song_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stems_song_id"), table_name="stems")
    op.drop_table("stems")
    op.drop_index("ix_jobs_user_id_state", table_name="jobs")
    op.drop_index("ix_jobs_song_id", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("songs")
    # ### end Alembic commands ###
