"""user_song_settings

Chapter 5's per-user, per-song player settings, saved automatically by the
player on every change (T-1.16).

The primary key is (user_id, song_id) rather than a surrogate: there is exactly
one row per person per song by definition, and saying so in the key means an
upsert cannot quietly create a second one.

`user_id` has no foreign key, for the same reason `jobs.user_id` does not - users
belong to a managed auth provider and D-16 is undecided.

Revision ID: a1f742e3cfbd
Revises: 1fe75bcef4e6
Create Date: 2026-08-20 10:31:07.407936

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1f742e3cfbd"
down_revision: str | Sequence[str] | None = "1fe75bcef4e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_song_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("key_shift", sa.SmallInteger(), nullable=False),
        sa.Column("tempo_ratio", sa.Float(), nullable=False),
        sa.Column("stem_volumes_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("lyric_offset_ms", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key_shift BETWEEN -6 AND 6", name=op.f("ck_user_song_settings_key_shift_range")
        ),
        sa.CheckConstraint(
            "tempo_ratio BETWEEN 0.5 AND 1.5", name=op.f("ck_user_song_settings_tempo_ratio_range")
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
            name=op.f("fk_user_song_settings_song_id_songs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "song_id", name=op.f("pk_user_song_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_song_settings")
    # ### end Alembic commands ###
