"""lyrics and lyric_lines

Chapter 5's words tables (T-2.1). `lyrics` is a *version* of a song's words, not
the words themselves: chapter 6 says an edit creates a new version rather than
overwriting, and (song_id, version) being unique is what makes that true of the
data and not only of the code that writes it.

`lyric_lines.words_json` is a blob rather than a third table. Words are only ever
read with their line and never queried across songs, so a table here would be a
join and a migration for something the player receives in one piece anyway.

Revision ID: c6782423e7f2
Revises: a1f742e3cfbd
Create Date: 2026-08-20 11:26:17.273775

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6782423e7f2"
down_revision: str | Sequence[str] | None = "a1f742e3cfbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lyrics",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('db', 'mix_asr', 'vocals_asr', 'manual')", name=op.f("ck_lyrics_source")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_lyrics_version_positive")),
        sa.ForeignKeyConstraint(
            ["song_id"], ["songs.id"], name=op.f("fk_lyrics_song_id_songs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lyrics")),
        sa.UniqueConstraint("song_id", "version", name="uq_lyrics_song_id_version"),
    )
    op.create_table(
        "lyric_lines",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lyrics_id", sa.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("end_ms", sa.Integer(), nullable=True),
        sa.Column("words_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "end_ms IS NULL OR start_ms IS NULL OR end_ms >= start_ms",
            name=op.f("ck_lyric_lines_end_after_start"),
        ),
        sa.CheckConstraint("index >= 0", name=op.f("ck_lyric_lines_index_positive")),
        sa.CheckConstraint(
            "start_ms IS NULL OR start_ms >= 0", name=op.f("ck_lyric_lines_start_ms_positive")
        ),
        sa.ForeignKeyConstraint(
            ["lyrics_id"],
            ["lyrics.id"],
            name=op.f("fk_lyric_lines_lyrics_id_lyrics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lyric_lines")),
        sa.UniqueConstraint("lyrics_id", "index", name="uq_lyric_lines_lyrics_id_index"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lyric_lines")
    op.drop_table("lyrics")
    # ### end Alembic commands ###
