"""The tables that exist so far: songs, stems, jobs, user_song_settings,
lyrics, lyric_lines.

Chapter 5 lists two more (library_items, usage_quota). They belong to the tasks
that use them and are deliberately not created here.

`Job.user_id` is a bare UUID with no foreign key. Users are owned by a managed
auth provider (D-16), the choice is still open, and a foreign key to a table
this project does not yet control would be a constraint we cannot honour.
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .db import Base
from .enums import (
    JobState,
    JobStep,
    LyricsSource,
    LyricsStatus,
    SongStatus,
    SourceType,
    StemKind,
)


def _uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID primary key generated by Postgres, and by Python before a flush.

    The server default is the one that matters: without it, every insert that
    does not go through the ORM - a migration backfill, a psql session, a repair
    script - has to remember to generate an id, and fails at 3am when it does
    not. `gen_random_uuid()` is built in from Postgres 13, so it costs no
    extension and does not tie D-15 to a particular host.
    """
    return mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )


class Song(Base):
    __tablename__ = "songs"

    id: Mapped[uuid.UUID] = _uuid_pk()

    title: Mapped[str] = mapped_column(Text)
    artist: Mapped[str | None] = mapped_column(Text)
    duration_sec: Mapped[int | None] = mapped_column(Integer)

    source_type: Mapped[str] = mapped_column(String(16))
    source_ref: Mapped[str | None] = mapped_column(Text)

    # sha256 of the normalised audio. Chapter 9 caps new songs per user per
    # month, and the cheapest song to process is one already processed, so this
    # is what a future dedup looks up. Unique, and nullable until ingestion has
    # actually read the file.
    content_hash: Mapped[str | None] = mapped_column(String(64))

    original_key: Mapped[str | None] = mapped_column(String(8))
    bpm: Mapped[float | None] = mapped_column(Numeric(6, 2))

    status: Mapped[str] = mapped_column(String(16), default=SongStatus.PENDING)
    # Not derivable from `status`: a song is playable once the stems are
    # encoded, which is one or two steps before it is READY. See SongStatus.
    is_playable: Mapped[bool] = mapped_column(default=False)
    lyrics_status: Mapped[str] = mapped_column(String(16), default=LyricsStatus.PENDING)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    stems: Mapped[list["Stem"]] = relationship(back_populates="song", cascade="all, delete-orphan")
    jobs: Mapped[list["Job"]] = relationship(back_populates="song", cascade="all, delete-orphan")
    lyrics: Mapped[list["Lyrics"]] = relationship(
        back_populates="song", cascade="all, delete-orphan"
    )

    __table_args__ = (
        CheckConstraint(f"source_type IN {tuple(str(v) for v in SourceType)}", name="source_type"),
        CheckConstraint(f"status IN {tuple(str(v) for v in SongStatus)}", name="status"),
        CheckConstraint(
            f"lyrics_status IN {tuple(str(v) for v in LyricsStatus)}", name="lyrics_status"
        ),
        # Chapter 9 caps song length at 8 minutes. Enforced in the API too, but
        # a row that violates it is a bug worth catching at the boundary.
        CheckConstraint("duration_sec IS NULL OR duration_sec <= 480", name="duration_max"),
        UniqueConstraint("content_hash", name="uq_songs_content_hash"),
    )


class Stem(Base):
    __tablename__ = "stems"

    id: Mapped[uuid.UUID] = _uuid_pk()
    song_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("songs.id", ondelete="CASCADE"), index=True
    )

    kind: Mapped[str] = mapped_column(String(16))
    # The object key, not a URL: chapter 6 hands out signed URLs per request and
    # a stored URL would be a stored expiry.
    storage_key: Mapped[str] = mapped_column(Text)
    format: Mapped[str] = mapped_column(String(16))
    bytes: Mapped[int] = mapped_column(Integer)

    song: Mapped[Song] = relationship(back_populates="stems")

    __table_args__ = (
        CheckConstraint(f"kind IN {tuple(str(v) for v in StemKind)}", name="kind"),
        # Four stems per song, one of each. A second `vocals` row means a
        # re-run wrote alongside the old one instead of replacing it.
        UniqueConstraint("song_id", "kind", name="uq_stems_song_id_kind"),
    )


class Job(Base):
    __tablename__ = "jobs"

    id: Mapped[uuid.UUID] = _uuid_pk()
    song_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("songs.id", ondelete="CASCADE"))
    user_id: Mapped[uuid.UUID] = mapped_column(PgUUID(as_uuid=True))

    state: Mapped[str] = mapped_column(String(16), default=JobState.QUEUED)
    current_step: Mapped[str | None] = mapped_column(String(32))
    progress: Mapped[int] = mapped_column(SmallInteger, default=0)

    # The handle on the remote GPU call. Chapter 5: without it there is no way
    # to follow the work once it has left this process.
    remote_call_id: Mapped[str | None] = mapped_column(String(128))
    # Measured on every job. Chapter 7 calls this the only way to know how much
    # free credit is left, and phase 0 found the credit was $1, not $30.
    gpu_seconds: Mapped[float | None] = mapped_column(Numeric(10, 3))

    error_code: Mapped[str | None] = mapped_column(String(64))
    # No automatic retry on a GPU step (chapter 7) - a retry costs double
    # credits, so it is the user's call. This counts the deliberate ones.
    attempts: Mapped[int] = mapped_column(SmallInteger, default=0)

    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    song: Mapped[Song] = relationship(back_populates="jobs")

    __table_args__ = (
        CheckConstraint(f"state IN {tuple(str(v) for v in JobState)}", name="state"),
        CheckConstraint(
            f"current_step IS NULL OR current_step IN {tuple(str(v) for v in JobStep)}",
            name="current_step",
        ),
        CheckConstraint("progress BETWEEN 0 AND 100", name="progress_range"),
        # D-25: there is no Celery and no Redis. The GPU platform is the queue
        # and this table is the status, which means "the user's live jobs" is a
        # query that runs on every progress poll and every quota check.
        Index("ix_jobs_user_id_state", "user_id", "state"),
        Index("ix_jobs_song_id", "song_id"),
    )


class UserSongSettings(Base):
    """How one person likes to sing one song (chapter 5).

    Saved automatically from the player on every change, which is what makes the
    key worth having: coming back to a song a week later and finding it already
    in your range is the difference between a tool and a toy.

    The primary key is (user_id, song_id) rather than a surrogate id. There is
    exactly one row per person per song by definition, and saying so in the key
    means an upsert cannot create a second one.
    """

    __tablename__ = "user_song_settings"

    user_id: Mapped[uuid.UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    song_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("songs.id", ondelete="CASCADE"), primary_key=True
    )

    # Chapter 8's ranges. Constrained here as well as in the player, because a
    # stored +40 would be applied by some future client that trusts the row.
    key_shift: Mapped[int] = mapped_column(SmallInteger, default=0)
    tempo_ratio: Mapped[float] = mapped_column(Float, default=1.0)

    # {"vocals": 0.0, "drums": 1.0, ...}. JSON rather than four columns because
    # the set of stems is a property of the separation model (D-05/D-06), and a
    # model that returns five stems should not need a migration.
    stem_volumes_json: Mapped[dict | None] = mapped_column(JSONB)

    # Phase 2, when there are lyrics to nudge. The column exists now because
    # chapter 5 lists it and adding it later is a migration for nothing.
    lyric_offset_ms: Mapped[int] = mapped_column(Integer, default=0)

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint("key_shift BETWEEN -6 AND 6", name="key_shift_range"),
        CheckConstraint("tempo_ratio BETWEEN 0.5 AND 1.5", name="tempo_ratio_range"),
    )


class Lyrics(Base):
    """One version of a song's words (chapter 5).

    A version, not *the* lyrics: chapter 6 says an edit creates a new version
    rather than overwriting, and this is where that is enforced. `version`
    counts from 1 per song and the highest one is what the player opens, so
    going back to a transcript someone regrets editing is a read, not a
    restore from a backup that was never taken.

    Deliberately not a column on `songs`. The same song can have an ASR
    transcript, a corrected version of it, and eventually a database match, and
    all three have to be able to coexist while the user decides.
    """

    __tablename__ = "lyrics"

    id: Mapped[uuid.UUID] = _uuid_pk()
    song_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("songs.id", ondelete="CASCADE"))

    # BCP-47-ish and short. Hebrew is the point of the project, but a Hebrew
    # singer's library has English songs in it, and the aligner (T-2.5) needs to
    # be told which.
    language: Mapped[str] = mapped_column(String(8), default="he")
    source: Mapped[str] = mapped_column(String(16))
    # Set by a person saying "these words are right", not by a confidence score.
    # T-2.4 records *which* transcript won in `source`; this is the human answer
    # to a different question, and the editor is what sets it.
    is_verified: Mapped[bool] = mapped_column(default=False)
    version: Mapped[int] = mapped_column(SmallInteger, default=1)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    song: Mapped[Song] = relationship(back_populates="lyrics")
    lines: Mapped[list["LyricLine"]] = relationship(
        back_populates="lyrics",
        cascade="all, delete-orphan",
        order_by="LyricLine.index",
    )

    __table_args__ = (
        CheckConstraint(f"source IN {tuple(str(v) for v in LyricsSource)}", name="source"),
        CheckConstraint("version >= 1", name="version_positive"),
        # What makes "a new version, never an overwrite" true of the data and
        # not only of the code that writes it. Two concurrent saves cannot both
        # become version 4; the loser retries and becomes version 5.
        # Every read is "the newest version of this song", and the index behind
        # this constraint is the one that answers it - a second index on the
        # same two columns would be a write cost for nothing.
        UniqueConstraint("song_id", "version", name="uq_lyrics_song_id_version"),
    )


class LyricLine(Base):
    """One line, with the timing the player scrolls by.

    Times are milliseconds from the start of the song, integers. Chapter 8 wants
    the current line highlighted within 100ms, so a float's worth of precision
    would be pretending, and the audio clock these are compared against is
    reported in seconds by the worklet - the conversion happens in one place in
    the browser rather than in the schema.

    `end_ms` is nullable: a line-level alignment that only found starts is a
    usable karaoke track, and inventing an end from the next line's start would
    make a guess indistinguishable from a measurement.
    """

    __tablename__ = "lyric_lines"

    id: Mapped[uuid.UUID] = _uuid_pk()
    lyrics_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("lyrics.id", ondelete="CASCADE"))

    # Position in the song, 0-based and contiguous. The order the lines are
    # sung, which is not the order of their ids and - for a line whose timing is
    # still missing - not the order of their start times either.
    index: Mapped[int] = mapped_column(Integer)
    text: Mapped[str] = mapped_column(Text)

    start_ms: Mapped[int | None] = mapped_column(Integer)
    end_ms: Mapped[int | None] = mapped_column(Integer)

    # [{"text": ..., "start_ms": ..., "end_ms": ...}]. Empty when the alignment
    # is line-level only, which chapter 7 treats as a normal outcome rather than
    # a failure. JSON rather than a third table: words are only ever read with
    # their line, never queried across songs, and a table would be a join and a
    # migration for something the player receives as one blob anyway.
    words_json: Mapped[list | None] = mapped_column(JSONB)

    lyrics: Mapped[Lyrics] = relationship(back_populates="lines")

    __table_args__ = (
        CheckConstraint("index >= 0", name="index_positive"),
        CheckConstraint("start_ms IS NULL OR start_ms >= 0", name="start_ms_positive"),
        CheckConstraint(
            "end_ms IS NULL OR start_ms IS NULL OR end_ms >= start_ms", name="end_after_start"
        ),
        UniqueConstraint("lyrics_id", "index", name="uq_lyric_lines_lyrics_id_index"),
    )
